# BEGIN_KITTY_THEME
# Gruvbox Dark
include kitty-theme.conf
# END_KITTY_THEME

# set shell
shell /usr/bin/fish

# set font
font_family      CaskaydiaCoveNFM-Regular
font_size        13.0
bold_font        auto
italic_font      auto
bold_italic_font auto

#paste behavior
mouse_map right press ungrabbed paste_from_clipboard

