# BEGIN_KITTY_THEME
# Gruvbox Dark
include kitty-theme.conf
# END_KITTY_THEME

# set shell
shell /usr/bin/bash

# set font
font_family      CaskaydiaCoveNFM-Regular
font_size        13.0
bold_font        auto
italic_font      auto
bold_italic_font auto

#paste behavior
enable_audio_bell no
copy_on_select no

# Clear default mouse actions if needed
clear_all_mouse_actions no

# Middle-click: Paste from Primary Selection (highlighted text)
mouse_map middle release ungrabbed paste_from_selection

# Right-click: Paste from System Clipboard (Ctrl+C / Cmd+C copy)
mouse_map right press ungrabbed paste_from_clipboard
