[ids]
*

[main]
# Keep all Meta/Super behavior intact
# Trigger the 'swapped' layer when pressing Meta + Caps Lock

[meta]
h = left
j = down
k = up
l = right
u = pageup
n = pagedown
b = backspace
r = delete
v = S-insert
capslock = toggle(swapped)

[swapped]
# Swap the behavior of Escape and Caps Lock in this layer
capslock = esc
esc = capslock
